# Nextest configuration for cuenv tests

[store]
# Store test results and artifacts
dir = "target/nextest"

[profile.default]
# Set reasonable defaults for all tests
slow-timeout = { period = "30s", terminate-after = 2 }
leak-timeout = "100ms"
test-threads = 16
retries = 0

# Store failure output for debugging
[profile.default.junit]
store-success-output = false
store-failure-output = true

# Process group cleanup test needs serial execution
[[profile.default.overrides]]
filter = "test(process_group_cleanup)"
threads-required = 1
slow-timeout = { period = "30s" }

# Cache and concurrent tests need limited parallelism
[[profile.default.overrides]]
filter = "test(concurrent) | test(cache)"
slow-timeout = { period = "10s" }

# Chaos engineering tests need more time but not infinite
[[profile.default.overrides]]
filter = "test(test_memory_pressure_chaos) | test(test_multi_vector_chaos)"
threads-required = 1
slow-timeout = { period = "60s", terminate-after = 2 }

# For CI runs, be more conservative to avoid TLS exhaustion
[profile.ci]
test-threads = 4                                        # Limit concurrency to prevent resource exhaustion
slow-timeout = { period = "120s", terminate-after = 3 }
leak-timeout = "200ms"
retries = 2
fail-fast = false

# Store all output for CI debugging
[profile.ci.junit]
store-success-output = true
store-failure-output = true
path = "target/nextest/ci-results.xml"

[profile.ci.junit.report]
store-test-output = true

# Ignore highly concurrent tests in CI to avoid TLS exhaustion
# Note: nextest 0.9.x doesn't support status = "skip", so we handle this with filtering instead

# Run integration tests serially in CI
[[profile.ci.overrides]]
filter = "test(integration) | test(comprehensive)"
threads-required = 1
slow-timeout = { period = "120s", terminate-after = 1 }

# Environment override test has race condition with concurrent execution
[[profile.ci.overrides]]
filter = "test(test_environment_overrides)"
threads-required = 1
slow-timeout = { period = "60s", terminate-after = 1 }

# Quick profile for development
[profile.quick]
test-threads = 16
retries = 0
fail-fast = true
slow-timeout = { period = "15s" }

# FFI tests need special handling due to Go-Rust boundary
[[profile.default.overrides]]
filter = 'package(cuenv-libcue-ffi-bridge)'
test-threads = 1
slow-timeout = { period = "30s" }

# Property-based tests can be slower
[[profile.default.overrides]]
filter = 'test(prop_) or test(property)'
slow-timeout = { period = "180s" }

# Coverage profile - single threaded for better accuracy
[profile.coverage]
test-threads = 1
retries = 0
slow-timeout = { period = "300s" }

# Stress testing profile
[profile.stress]
test-threads = 16
slow-timeout = { period = "60s", terminate-after = 1 }
retries = 0

[test-groups]
# Group tests that conflict on resources
serial-tests = { max-threads = 1 }
ffi-tests = { max-threads = 1 }
integration-tests = { max-threads = 2 }
